### ISSUE TITLE
Form fields filter

### ISSUE THREAD

**Issue by domas-tld** [hallme/woo-address-book#1]
Hi there,

Great plugin, but how can I filter "shipping2" form fields? E.g. I use **woocommerce_billing_fields** and **woocommerce_shipping_fields** filters to tweak form labels and placeholders.

Thanks,
Domas

**Comment by gthayer** [comment]
Hmm, that's a good question!

You can modify the filter to change a specific address:

`function filter_woocommerce_shipping2_fields( $wooccm_shipping_fields, $int ) { 

   	$wooccm_shipping_fields['shipping2_first_name']['label'] = 'New Label';

    return $wooccm_shipping_fields; 
}; 

// add the filter 
add_filter( 'woocommerce_shipping2_fields', 'filter_woocommerce_shipping2_fields', 10, 2 );`

However, this does not work for all addresses stored in the address book. What if there is a shipping3 or shipping4?

Thanks for the report! We'll need to look into a patch.

**Comment by TimBHowe** [comment]
Hey Domas,
For the time being this should work to solve your issue:
`// define the woocommerce_form_field_args callback 
function filter_woocommerce_form_field_args( $args, $key, $value ) {
    if( preg_match( '/(shipping|billing)(\d{1,})?_first_name/', $args['id'], $match ) ) {
        $args['label'] = 'TODO:new label';
        $args['placeholder'] = 'TODO:new placeholder';
    }
    return $args;
}
add_filter( 'woocommerce_form_field_args', 'filter_woocommerce_form_field_args', 10, 3 );`

This function should allow you to target fields by their ID as they are being built to modify their label and placeholder.  Just updated '_first_name' in the preg_match to target the field you want.

We will look at updating the plugin to allow the **woocommerce_shipping_fields** to work probably, but it will take some time.

Please let us know if you have any other questions

**Comment by gthayer** [comment]
#2

**Comment by gthayer** [comment]
Issue solved in version 1.1
