### ISSUE TITLE
Error message: "Please provide a valid email address" 

### ISSUE THREAD

**Issue by PeterPopanz** [hallme/woo-address-book#10]
Hi,

in the following scenario I get the error message "Please provide a valid email address" at checkout:
- The address book plugin is activated, 
- I will send to a diffent shipping address, 
- I select "Add New Address" in the address selector, 
- of course there is a valid email address in the billing address fields.

If I select an existing shipping address from the selector, no problems.

Thank you for your help.

**Comment by gthayer** [comment]
Thanks for your report!

Do you have an example of this you can share? I have not been able to replicate it on twentyseventeen with the most recent version of Woo.

Have you tired it with another theme or deactivating other plugins?
