### ISSUE TITLE
Add birthday field

### ISSUE THREAD

**Issue by moh-ar** [hallme/woo-address-book#106]
Thanks for this excellent plug-in, I hope it has birthday field with the possibility for email reminders 
This would have good impact in increasing sales

**Comment by matt-h** [comment]
While birthday reminders would be a good feature for WooCommerce, that is out of the scope of this plugin. It could probably be a plugin on its own.

You can already add custom fields such as a Birthday field that will be compatible with this plugin either manually with this: https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/
Or through the admin with a plugin like this: https://woocommerce.com/products/woocommerce-checkout-field-editor/

As far as email reminders. Either AutomateWoo https://woocommerce.com/products/automatewoo/
Or the AutomateWoo birthday reminders extension: https://woocommerce.com/products/automatewoo-birthdays/
could help you work towards building that.
