### ISSUE TITLE
Certain addresses in the database are not matching the addresses at checkout

### ISSUE THREAD

**Issue by adrianbgo** [hallme/woo-address-book#113]
I have received an issue from some of the users of my organization's site that when they go through the checkout process, after the checkout is submitted, their address changes. Upon looking into the database, it appears that instead of having a key in the format of:
```
shipping_parameter
```
it instead has a key in the format of:
```
_parameter
```
Somehow for some of the users, an incorrect/mistyped address is being assigned to their user with no prefix and it's causing an incorrect address to be submitted after checkout. We are now having to pay UPS to correct the address so that the products don't ship to the wrong address.

**Comment by matt-h** [comment]
Hi, sorry to hear you are having issues with this.

I don't see how this plugin could be affecting the addresses on the order themselves. It doesn't change the existing checkout fields from WooCommerce itself, it just auto-fills the existing ones when you select an address. It also doesn't hook into anywhere to affect order saving.

If you have more details we can look further.

**Comment by adrianbgo** [comment]
Thank you for the quick response! Apologies if I've posted an issue that doesn't have to do with your plugin. To give more detail, the address that's being inserted appears to be an incorrect address that was originally added to the address book and then removed. However, that address remains in the database, just without a "nickname" and is overriding the selected address. If this is not an issue with your plugin, then feel free to close the issue. For context, our site is using version 1.7.5

**Comment by matt-h** [comment]
I can't think of any way that would be possible to happen with the way this plugin works, but if you are able to provide a way we can re-produce the issue then we can take a look further.
