### ISSUE TITLE
blockUI dependency not specified

### ISSUE THREAD

**Issue by SebastianTusk** [hallme/woo-address-book#119]
On my installation the following error occurs.
```
Uncaught TypeError: $.blockUI is undefined
at /wp-content/plugins/woo-address-book/assets/js/scripts.min.js?ver=2.1.0:1
```
This happens because the woo-address-book js script is executed before blockUI. Adding the dependency at https://github.com/hallme/woo-address-book/blob/ddcee01be8e28d6e0b1d900367e4df823c7d6bad/includes/class-wc-address-book.php#L184
fixes the issue.
With blockUI dependency:
```
wp_register_script( 'woo-address-book', plugins_url( "/assets/js/scripts$min.js", dirname( __FILE__ ) ), array( 'jquery', 'jquery-blockui' ), $this->version, true );
```

**Comment by matt-h** [comment]
Thanks for this @SebastianTusk 
An update has been released that adds this.
