### ISSUE TITLE
removing required field

### ISSUE THREAD

**Issue by daron4ever** [hallme/woo-address-book#12]
Hello,
I removed required shipping_city field from Woocommerce default Edit at My Account page.
But, I need help to remove required shipping_city field from Edit/Add at My Account page.
Regards,

**Comment by gthayer** [comment]
Are you removing the field, or the requirement?

This should work for removing the field:

`function remove_city_field($fields) {

    unset( $fields ['city'] );
    return $fields;
}

add_filter( 'woocommerce_default_address_fields', 'remove_city_field' ); `

**Comment by daron4ever** [comment]
Remove the field.
It works. Thank you!
