### ISSUE TITLE
How to update an existing address?

### ISSUE THREAD

**Issue by edrisranjbar** [hallme/woo-address-book#126]
Hi there, how can I update an existing address. like I open `http://localhost/wordpress/my-account/edit-address/billing/?address-book=billing2` and I can get the values (i am customizing the whole `form-edit-address.php`).

## here's my code:
```
	$wc_address_book = WC_Address_Book::get_instance();
	$woo_address_book_customer_id = get_current_user_id();
	$woo_address_book_billing_address_book  = $wc_address_book->get_address_book($woo_address_book_customer_id, 'billing');
	$address_infromation = $woo_address_book_billing_address_book['billing'];
```

I can display values in input tags, but I cant update that particular address.

**Comment by matt-h** [comment]
The plugin uses the [`update_address_names`](https://github.com/hallme/woo-address-book/blob/10435877363678efcdde7614c32c3327d9b20019/includes/class-wc-address-book.php#L433) function to add a new address entry, only adding the additional entry.

The [`replace_address_key`](https://github.com/hallme/woo-address-book/blob/10435877363678efcdde7614c32c3327d9b20019/includes/class-wc-address-book.php#L981) function updates the WooCommerce name keys from the default when creating the form.

However, all of the saving of the actual address falls on WooCommerce and is outside this plugin. The [`save_address`](https://github.com/woocommerce/woocommerce/blob/67d9ba3b19eac09c98aa4bed2c29231c4dd2fc1c/plugins/woocommerce/includes/class-wc-form-handler.php#L79) in WooCommerce is what actually saves the address fields.

**Comment by matt-h** [comment]
My guess is you would have to either call the WooCommerce [`save_address`](https://github.com/woocommerce/woocommerce/blob/67d9ba3b19eac09c98aa4bed2c29231c4dd2fc1c/plugins/woocommerce/includes/class-wc-form-handler.php#L79) form.
Or re-implement that yourself.

I'm not really sure, but I think if you included the proper `woocommerce-edit_address` `nonce` functions for `save_address` then the WooCommerce code will still run.
