### ISSUE TITLE
Address book workflow update request: Tab function not woking on state selection in shipping check out. 

### ISSUE THREAD

**Issue by thelittlewineguy** [hallme/woo-address-book#136]
The client has reported when they add addresses for customer information, they used the tab button to move through the shipping checkout form in woocommerce. When getting to the state selection for shipping, the tab button no longer selects the option for typing an in the search box for the state. 

Please advise for customer workflow.  video feedback below from the client below. 

https://app.userback.io/viewer/3882/74147/2183090VLLWPHJ8/

**Comment by matt-h** [comment]
I don't get the same behavior in the video on our test sites.

Can you verify if the same issue happens without the Address Book plugin active? The actual address fields are handled by WooCommerce itself and not this plugin as this plugin only handles managing multiple addresses. So, if the same issue happens without the plugin active then it would be something unrelated to this plugin.

**Comment by thelittlewineguy** [comment]
Thank you for the update!

**Comment by matt-h** [comment]
Closing this issue. If you have more information later feel free to add a comment.
