### ISSUE TITLE
AJAX calls don't work when shipping is disabled

### ISSUE THREAD

**Issue by nicolasmn** [hallme/woo-address-book#14]
AJAX functions are scoped to the `.address-book` selector which isn't present on MyAccount page when shipping is disabled in WooCommerce. See #13

**Comment by gthayer** [comment]
Looking into this, I have a few questions:

- I've not been able to replicate this exactly. Can you post a screenshot of your WooCommerce settings? When shipping address is forced to be the same as billing address, the address book bugs out (needs fix). But if no shipping zones are used, AJAX continues to work.

- Under what circumstances would you want the shipping address book, if shipping is disabled? The plugin does not work for billing addresses. I'm currently of the mind that the address book shouldn't function at all.
