### ISSUE TITLE
Plugin compatibility between WooCommerce Address Book and  WPC Fly Cart for Woocommerce

### ISSUE THREAD

**Issue by Data-Zombie** [hallme/woo-address-book#142]
Hello there,
for some reason customer select address from the drop down but the woocommerce field on woocommerce is now showing the selected address chosen from the customer.
Do you have any idea?

**Comment by matt-h** [comment]
Hi, can you clarify what you mean here? I'm not understanding what the issue is.

**Comment by Data-Zombie** [comment]
Hi Mat,
I'm using WPC Fly Cart for Woocommerce PRO with Instant checkout.
I would like to give to the customer the ability to select different shipping address depending where they want to receive the goods.
I have installed WooCommerce Address Book and I have noted that when a customer choose an available address from the dropdown, then the shipping information about the address selected is not showing up on the fields like woocommerce_first_neme woocommerce_last_name address ext.....
My question: is that a problem of compatibility?

<img width="692" alt="#1" src="https://user-images.githubusercontent.com/121128791/208761102-2a3c8b8f-a62a-4f52-9d81-a1be37c7f27b.png">
<img width="677" alt="#2" src="https://user-images.githubusercontent.com/121128791/208761113-bef8bc0b-e6bd-4244-91a7-1b4116df9dc0.png">

**Comment by matt-h** [comment]
Thanks for the Screenshots. I'd never heard of this plugin you are using before.

My best guess is because it is loading the checkout on other pages than the checkout page it isn't loading our checkout scripts. This scripts are what allow the dropdown to populate the address.

You could try loading the address book scripts on every page on your site.
A custom action like this should work to do that.

```
add_action( 'wp_enqueue_scripts', 'custom_address_book_scripts', 20 );
function custom_address_book_scripts() {
    wp_enqueue_script( 'woo-address-book' );
}
```

**Comment by Data-Zombie** [comment]
It load but is showing up address informations.
The website is fgnhq.com
It is not in production but need to login so you can use user: 1001640 and psw Test123!
Let me know if this help. Thanks

**Comment by matt-h** [comment]
Okay, I was able to check that.

It seem that the address fields you have in there are all set to readonly so it can't edit those.

I just released version 2.4.0 of the plugin which should support updating those fields.

**Comment by Data-Zombie** [comment]
Yes I know I did it.
That fields I need to be readonly. That's because we'll add the address book in backend and customer need only to select where they need the goods to be shipped to.
But even if I remove the readonly PHP code shipping fields didn't autocomplete.
I have just update to v.2.4

**Comment by matt-h** [comment]
Ah, I forgot to mention it included a new checkbox in the admin that you'll need to make sure is Unchecked and then save the settings which should start allowing readonly fields to work.
![2022-12-20_856x652](https://user-images.githubusercontent.com/664294/208778937-8ef157d1-fcb3-4416-aad1-f409b72d30e8.png)

**Comment by Data-Zombie** [comment]
Checkbox is unchecked.
Function is active but for me doesn't happened.
Don't know why but that fields looks like freeze.
If you want I can shere in private admin credentials. Web site is not in production.

**Comment by Data-Zombie** [comment]
Hello Mat,
I just clear cookie and navigation datas and it works fine.
Thanks a lot for your support.

**Comment by matt-h** [comment]
Good to hear that it is working now!

**Comment by Data-Zombie** [comment]
Hello Mat,
just doing a few test on it.

I have injected this code into child theme function.php

add_action( 'wp_enqueue_scripts', 'custom_address_book_scripts', 20 );
function custom_address_book_scripts() {
    wp_enqueue_script( 'woo-address-book' );
}

It works for the first items added to the cart but if I remove the items and then add again other fields are not active.
I have a video to show better the case.
What do you think?

https://user-images.githubusercontent.com/121128791/210246815-c38e1e3d-a968-4ad7-b4b5-4620c2bd246e.mp4
