### ISSUE TITLE
Allow functionality for using company name or first- and last- name.

### ISSUE THREAD

**Issue by opicron** [hallme/woo-address-book#19]
When using an customized Woocommerce b2b where for shipping the company name is mandatory and first and last name are optional the address book selector on the checkout page is incorrect.

I have adjusted the code to allow using company names instead of first- and -last name when applicable.

For this I have added/changed the following code:

[function address_select_label] in [woocommerce-address-book.php] line 559.

$company = ( $address[$name . '_company'] ? true : false );
if ($company)
	$label = $address[$name . '_company'];
else				
	$label = $address[$name . '_first_name'] . ' ' . $address[$name . '_last_name'];

Could you please incorporate this in the plugin? Accompanied with an override setting which can enable this additional code to force maintaining backwards compatibilty.

Regards,
Robbert

**Comment by gthayer** [comment]
Thanks for the suggestion @opicron. I'll look into wrapping the output with a filter which should allow anyone to modify it as needed.

**Comment by gthayer** [comment]
Hi @opicron, I've got a new branch which I think will serve your needs:

https://github.com/hallme/woo-address-book/tree/code-cleanup

If you update to this version, and add the following function to `functions.php`, you should be able to adjust the shipping labels all you wish.

```
/**
 * Adds the address book select to the checkout page.
 *
 * @param array  $label - The assembled address label.
 * @param array  $address - An array of WooCommerce Shipping Address data.
 * @param String $name - The name of a specific address in the address book.
 */
function my_wc_address_book_address_select_label( $label, $address, $name ) {

	if ( ! empty( $address[ $name . '_company' ] ) ) {
		$label = $address[ $name . '_company' ];
	} else {
		$label = $address[ $name . '_first_name' ] . ' ' . $address[ $name . '_last_name' ];
	}

	return $label;
}
add_filter( 'wc_address_book_address_select_label', 'my_wc_address_book_address_select_label', 20, 3 );```

I've modified the `wc_address_book_address_select_label` filter to add `$address` and `$name`, which should open a lot of options for modifying the output.

Please let me know if this works for you, and I'll update the plugin on the repo.

Thanks!

**Comment by opicron** [comment]
Sorry for delay! I will check this shortly. Thank you for your support, much appreciated!

**Comment by opicron** [comment]
Awesome, it works perfect!
