### ISSUE TITLE
Warning: A non-numeric value encountered in woocommerce-address-book.php on line 228

### ISSUE THREAD

**Issue by rwilsond** [hallme/woo-address-book#21]
Installed this plugin today. Saw this on the "edit-address" page.

Warning: A non-numeric value encountered in woocommerce-address-book.php on line 228

My guess it has something to do with PHP 7+

Here's my config:

WC Version: 3.3.3
WP Version: 4.9.4
PHP Version: 7.1.8

**Comment by gthayer** [comment]
Thanks for the report! Looks like an empty string was being used instead of a zero. 

Just patched it, and merged into master. I've got some other edits I need to QA, but will have this up in the WP repo soon.
