### ISSUE TITLE
Multi-site support not working

### ISSUE THREAD

**Issue by gitnz** [hallme/woo-address-book#24]
Hello,

It seems that multi-site support isn't working for this plugin, whether it is activated on an individual site or network activated. I have downloading 1.3.4-dev from git, and I'm running WP 4.9.4.

I can force it to activate by disabling the following line:

`// Check if WooCommerce is active.
if ( 1 or in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ), true ) ) {`

Please note that get_option('active_plugins') returns an empty array, so there must be a different array used for multi-site enabled plugins. Sorry I'm not a WP developer so I don't know all aspects of the API.

Hoping you can help, thanks for your hard work!

**Comment by gthayer** [comment]
Thanks for the report. I think I just I've got the patch. https://github.com/hallme/woo-address-book/pull/26/commits/3ea9f6531066f5391acd85647893581b2a707b5f

I think that line was redundant. Let me know if this works for you.

**Comment by gthayer** [comment]
This patch is now live on the WordPress repo. Please let us know if you continue to have any issues.
