### ISSUE TITLE
Address Book not working 

### ISSUE THREAD

**Issue by GetFoundByDesign** [hallme/woo-address-book#25]
I am adding new user through core WordPress Users with a "Bill-To" and "Ship-To" address. We sell wholesale to Dealers who often have multiple stores i.e. ship-to address.  When I go to their profile (using their login) I see the primary ship to address. I try to add a 2nd ship-to to the address book, it accepts the address but does not actually show up in the address book.  Then I tried placing an order and selected add new address and it seemed to then fill in the new address from memory, or maybe the address book, but then I get an error message saying country is required when both the ship-to and bill-to indicate USA as the country.  What am I doing wrong?
WP v4.9.4
WOO Commerce v3.3.3
WooCommerce Address Book v1.3.3
URL: store.soflomattress.com

![addressbook-1](https://user-images.githubusercontent.com/36545145/36863897-0436d12a-1d59-11e8-8358-49c222f5ee2e.jpg)
![addressbook-2](https://user-images.githubusercontent.com/36545145/36863899-0450b2ca-1d59-11e8-8231-356e1ee55a53.jpg)
![addressbook-3](https://user-images.githubusercontent.com/36545145/36863900-046836d4-1d59-11e8-97d3-bd6efd1b17fd.jpg)

Thanks,
MaryAnn@SofloMattress.com

**Comment by gthayer** [comment]
Thanks for the report, I am going to close out this ticket because I see your other note on WordPress.org. I'll reach out there. Thanks!
