### ISSUE TITLE
How to add a custom field

### ISSUE THREAD

**Issue by ehmarketing** [hallme/woo-address-book#3]
Hi, 
It is a great plugin. I wonder how to add a custom field on the shipping address form such as phone number, note and so on.
Please kindly advise me.
Thank you!

Cheers,
Daniel

**Comment by gthayer** [comment]
Hi Daniel, thanks for the feedback!

Currently, there is a bug which prevents this, however there are a few solutions:

https://github.com/hallme/woo-address-book/issues/1

We also have a branch which might solve this entirely for you:

https://github.com/hallme/woo-address-book/tree/get-var

With this branch, you should be able to add custom fields in the standard WooCommerce way. Please take a look, and let us know if it works!

**Comment by ehmarketing** [comment]
The branch works perfectly!!What a brilliant!
Thank you so much!

**Comment by gthayer** [comment]
Issue solved in version 1.1
