### ISSUE TITLE
If adresse book is empy address name should be shipping and not shipping2

### ISSUE THREAD

**Issue by ebelrose** [hallme/woo-address-book#31]
https://github.com/hallme/woo-address-book/blob/2766c97da887da9ead01e23456b044aeefc863b5/woocommerce-address-book.php#L248

**Comment by gthayer** [comment]
I'll double check on this, but there was a very specific reason this is set to "shipping2". The Address Book plugin tries to only effect additional addresses beyond Woo's default address settings.

Are you running into a bug related to this?
