### ISSUE TITLE
Share addresses with multiple/all users

### ISSUE THREAD

**Issue by Source3Media** [hallme/woo-address-book#32]
Is there any ability to share all addresses in the address book with all users on the site? I have a client needing this feature and this plugin is the closest I've found. Please let me know if there is or if it's being worked on or even if I could extend the plugin myself.

**Comment by gthayer** [comment]
There is not a means of doing this directly, but I've just added a filter in 5f9ab31742403f4244ed6fad89afaae1cced4fa4 which should allow you to hook into the address book and replace it with the addresses you'd like.
