### ISSUE TITLE
State / County is a required field.

### ISSUE THREAD

**Issue by killlaherz** [hallme/woo-address-book#33]
I have this message when I try to add address from my account. It says state is required but there is no such field. The address can be added from checkout page however. The state field is not there as well, but here it does not block the adding. Can you help with this issue, how to make plugin think the state field is not neccessary in my account.

**Comment by gthayer** [comment]
Off hand, I'm not sure. This plugin does not define which fields display, or whether or not they are required. Can I see an example?

Have you modified any of the fields? Under what conditions do you not have a state field on the checkout?

**Comment by killlaherz** [comment]
![git1](https://user-images.githubusercontent.com/39748342/40730174-55b4c43c-642e-11e8-9797-010f5446a750.jpg)

This problem does not appear in checkout. This problem appears in my-account / Address Book. Since this was added by the plugin I assumed it is responsible for how the fields are displayed there. 

As you can see on the picture - there is no "state" field in the address book yet the plugin wants me to fill it. Byt the plugin does not want me to fill it if I add address to address book in checkout. 

I tried to select this field as not required in the woocommerce booster but that didn't help. Seems like I either need the "state" field in address book back (to be able to fill it) or I need to select this field as optional, not required. No idea how to do that and this is why I created this thread.

**Comment by gthayer** [comment]
Thanks for the extra info. I'll take a look and see if I can replicate it.

I'm not exactly sure what you mean by "WooCommerce Booster". Is it this plugin?https://wordpress.org/plugins/woocommerce-jetpack/

I don't have experience with that plugin, it may be that there is a conflict between Woo Address Book and this tool.

**Comment by killlaherz** [comment]
Yes . this is this plugin. I has an option to make some fields optional, not required and I tried to use it to make "state" optional. But it was only after this problem emerged. Anyway it didn't do anything.

**Comment by gthayer** [comment]
I think I see the problem. If the URL has a trailing slash when creating a new address, the slash is getting saved in the address's name in the database and the form fields.

Because of this, WooCommerce's default field events are not firing correctly. This is why the requirement based on country is still active when you switch.

I'm working on a patch here: https://github.com/hallme/woo-address-book/tree/address-page-JS-events

This should allow for new addresses to save correctly, however existing addresses with bad saved data will not work right. I'll need to look into fixing all of those.

**Comment by killlaherz** [comment]
Not sure if I understood you correctly. The problem is about county/state field, not country.

**Comment by gthayer** [comment]
I understand that, however the rules which define whether county/state are required is based on country. USA requires state, but Austria does not. Instead, Austria has a Province field.

Have you tried it with the updated branch? I'm curious whether the issue continues to occur.

**Comment by gthayer** [comment]
I've released 1.4. Hopefully this patch takes care of this for you.
