### ISSUE TITLE
Error after update when saving additional addresses

### ISSUE THREAD

**Issue by d3washout** [hallme/woo-address-book#34]
I am getting the following errors after the last woocommerce update.

Notice: Undefined index: shipping_country in /homepages/35/d725998930/htdocs/app745875614/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 94

Notice: Undefined index: shipping_country in /homepages/35/d725998930/htdocs/app745875614/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 129

Notice: Undefined index: shipping_country in /homepages/35/d725998930/htdocs/app745875614/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 132

Warning: Cannot modify header information - headers already sent by (output started at /homepages/35/d725998930/htdocs/app745875614/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php:94) in /homepages/35/d725998930/htdocs/app745875614/wp-includes/pluggable.php on line 1219

Any ideas?  Thanks

**Comment by gthayer** [comment]
This is a known bug, but only matters when wp_debug is on:

https://github.com/hallme/woo-address-book/issues/4

Very annoying on staging, but shouldn't effect production sites.
