### ISSUE TITLE
Have you fixed the bug where the Address Search bar doesn't show when there is no Default?

### ISSUE THREAD

**Issue by Stumsy** [hallme/woo-address-book#35]
I am looking at using this plugin and saw a previous problem where this was acknowledged as a bug.

For first time users, we don't want to display the Search Address bar - and want the first address they enter to be saved as the Default (can this be done with a checkbox to ask if they want to keep an Address Book or not?)

Stuart

**Comment by gthayer** [comment]
This has not been fixed yet. This project has been on hold for a bit. I'm hoping to put some time into it soon, however if you are under any time constraints I would recommend not using this plugin.
