### ISSUE TITLE
import feature

### ISSUE THREAD

**Issue by dmahaffey** [hallme/woo-address-book#37]
I'd like to use the address book feature in tandem with the multi shipping plugin.  

https://woocommerce.com/products/shipping-multiple-addresses/

Their plugin allows shipping one product to multiple addresses (such as a gift or post card).  

However my customers will probably add a lot of addresses. Do you have plans of including an import feature that will allow those addresses to be imported via CSV instead of adding them one by one?

**Comment by gthayer** [comment]
I've not tested Woo Address Book with this plugin, so I'm not certain how well they'll work together.

I'd agree that adding a CSV import tool would be great, but we don't have any plans to add new features at this time. If someone wanted to build one, we'd certainly review and potentially merge it in.
