### ISSUE TITLE
Empty form shown when user has no default address

### ISSUE THREAD

**Issue by jamesfawcett** [hallme/woo-address-book#38]
When the user has no default shipping address, e.g. if they registered without making a purchase, they are still shown the **add new shipping address** on the my account Edit Address page.

When clicking this button, you are taken to a page with a blank form.

If the user returns, and clicks the edit button and sets a shipping address first, then the **add new shipping address** button works correctly.

To fix, I changed the following function:

```
/**
		 * Adds a link/button to the my account page under the addresses for adding additional addresses to their account.
		 *
		 * @since 1.0.0
		 * @since 1.4.0 Check for default shipping address before showing button
		 */
		public function add_additional_address_button() {

			$user_id       = get_current_user_id();
			$address_names = $this->get_address_names( $user_id );

			$name = $this->set_new_address_name( $address_names );

			if ( WC()->customer->get_shipping_postcode() ):
			?>

			<div class="add-new-address">
				<a href="<?php echo esc_url( wc_get_endpoint_url( 'edit-address', 'shipping/?address-book=' . $name ) ); ?>" class="add button"><?php echo esc_html_e( 'Add New Shipping Address', 'wc-address-book' ); ?></a>
			</div>

			<?php
			endif;
		}
```

Is there any chance this could be merged in, or could I create a pull request?

**Comment by matt-h** [comment]
Hi @jamesfawcett 

Sorry for taking so long to look into your issue.

We believe this should be fixed  in a different way in the latest release. Please let us know if you are still having the issue and we can look into it further.

Matt
