### ISSUE TITLE
Volume Limit "woo-address-book"? 100 addresses?

### ISSUE THREAD

**Issue by ITAAU** [hallme/woo-address-book#41]
"woo-address-book" wont add more address's and just modify one. Is there a limit of approximately 100 addresses? Any advice would be appreciated?

**Comment by matt-h** [comment]
Hi @ITAAU thank you for the report
This should be fixed by https://github.com/hallme/woo-address-book/pull/47

You can update to 1.5.0
Let us know if you are still having issues after updating.
