### ISSUE TITLE
Incorrect RegEx causes issues for users with >= 10 addresses

### ISSUE THREAD

**Issue by JonBoss5** [hallme/woo-address-book#42]
I came across this issue using the plugin on a client's site, it occurs when a user has a shipping address > 9, and creates or edits an address. Its due to the regular expression that standardizes the field IDs, and results in Woocommerce's state/province field not updating when the country changes. The line in question is:

woocommerce-address-book.php:785

`$args['id'] = preg_replace( '/^shipping[^_]/', 'shipping', $args['id'] );`

The regular expression will only replace the first digit after 'shipping'. Results in 'shipping12_first_name' => 'shipping2_first_name'

Expression should probably be: ^shipping[^_]+ with a plus.

In addition, this function (standardize_field_ids) fires on the hook 'woocommerce_form_field_args' which is added as an action, but should be added as a filter. Line 107 of the same file.

Hope that helps!

**Comment by matt-h** [comment]
Thanks for the report here with the fix. We have just released version 1.5.0 of WooCommerce Address Book which includes your fix for this.
