### ISSUE TITLE
Add new shipping address empty - my account

### ISSUE THREAD

**Issue by SamXronn** [hallme/woo-address-book#51]
With a stored shipping address already I click the "Add new shipping address" button and the next page is empty. The "woocommerce-address-fields__field-wrapper" is empty I only get a save button no input fields.

WooCommerce: **3.6.2**
WooCommerce Address Book: **1.5.1**

**Comment by matt-h** [comment]
Hi @SamXronn 

We are unable to reproduce this issue in our testing.

Do you have any more information about your setup for anything that might be conflicting with our plugin?

**Comment by SamXronn** [comment]
Thanks for getting back to me, I'm not sure if you have compiled a conflicting plugins blacklist, other notable plugins would be;

Custom Product Tabs for WooCommerce **1.6.10**
WooCommerce Save & Share Cart **2.19**

Both freely available plugins if you have a sandbox be interesting to see if you could reproduce the issue with either of these, thanks.

**Comment by SamXronn** [comment]
I've disabled all plugins on my site and the issues persist, could there be a theme compatibility issue?

**Comment by matt-h** [comment]
Very possible it could be something with the theme. If you have a site with it happening on that I can see, that might help figure it out. I've tried various settings and can't reproduce the issue so far.

If you don't want to share it on github, you can email me at matt@hallme.com

**Comment by matt-h** [comment]
Hi @SamXronn 

We still have not been able to reproduce the issue that you are having. However, we just released 1.5.4 of the Woo Address Book which has a lot of improvements to the address saving code of the plugin. If you could give this new version a try and let us know if it fixed it for you or you are still having the issue with the fields showing up?
