### ISSUE TITLE
Switch primary address bug fix

### ISSUE THREAD

**Issue by ThomasK0lasa** [hallme/woo-address-book#53]
https://github.com/hallme/woo-address-book/blob/2c1c57dfc19ad6e4391eff1068fdf68ac3afe03a/assets/js/scripts.js#L62

Currently line 62 of scripts.js should be "url: woo_address_book.ajax_url," instead of "url: wc_address_book.ajax_url," - otherwise switching primary address doesn't work.

**Comment by matt-h** [comment]
Thanks @ThomasK0lasa for reporting this issue.

I just released 1.5.3 with this fix included.

**Comment by ThomasK0lasa** [comment]
@matt-h np :)
I am not sure how the wordpress translation system works, but can I ask You to accept the polish translation for this plugin? I doubt if someone else will accept it in closest time.

**Comment by matt-h** [comment]
I'm not exactly sure how the translation system works either. I can't accept it, I think only editors on the translation team can. I'm not sure how long it takes.

I think you can run them locally by going to your translation at https://translate.wordpress.org/projects/wp-plugins/woo-address-book/stable/pl/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting
and using the Export button at the bottom to download a .po or .mo file

And save it at `/wp-content/languages/plugins/woo-address-book-pl.mo` or `/wp-content/languages/plugins/woo-address-book-pl.po` for it to load.

I've never done it so I don't know exactly how it works.

**Comment by ThomasK0lasa** [comment]
Thank You @matt-h, sadly this doesn't work for me - the translation files. Seems like they are not loaded. Not sure what I ma doing wrong, the translation files in WP are new to me. For today I am done, I will get back to it tomorrow. :)
Anyway thank You for the help and sorry for off topic.

**Comment by evangwin** [comment]
Just to make sure I understand this.  Was this fix to allow the primary address aka billing address to be changed on the checkout page via a dropdown like can be done with the shipping address?

**Comment by matt-h** [comment]
@evangwin This is for the Primary Shipping address. The address book plugin currently only lets you manage an address book for Shipping Addresses and not billing.
Some day we would like to add the ability to manage billing addresses as well, but we have no idea when that would be.

**Comment by evangwin** [comment]
@matt-h What is the difference in code between adding the drop down box for the shipping and billing?  Look forward to having the ability to edit box with the address book.

**Comment by matt-h** [comment]
@evangwin We don't know what it would take to get it to work with billing yet. It is not something that we've looked into at all.
