### ISSUE TITLE
Create account on checkout, address book empty 

### ISSUE THREAD

**Issue by jellewebsols** [hallme/woo-address-book#55]
Steps to reproduce:
- Woocommerce is set to allow account creation on checkout
- Add product to cart and go to checkout
- Fill in billing and shipping address on checkout page
- Place order
- Go to my account page
- Address book empty 

After placing the order I see _shipping2_ meta records are created in the database, but it looks like the **wc_address_book** user meta is missing.

If we then create a new shipping address and save it (thus creating a **wc_address_book** user meta), the previous address from checkout also appears.

**Comment by matt-h** [comment]
Thanks for your report. We have been able to reproduce this issue and are working on a fix. We'll let you know when we have released a new version with this issue fixed.

**Comment by matt-h** [comment]
We just released 1.5.4 which should fix this issue. Please let us know if you are still having the issue.

**Comment by jellewebsols** [comment]
Thank you for the update, working as expected now!
