### ISSUE TITLE
Address book is not showing in the checkout

### ISSUE THREAD

**Issue by harshitmahendra** [hallme/woo-address-book#64]
I have added the latest version of woo-address-book which is 1.7.1 

I added the plugin to my WordPress site. Then I added a new address in the address book when I go to my checkout page I didn't have an address book option to select!

**Comment by matt-h** [comment]
Hi, the plugin uses the standard WooCommerce filters to add the custom field.

Do you have any plugins or custom theme modifications that edit your checkout fields or change the order?

Any info you can provide about your environment will help in diagnosing the conflict.
