### ISSUE TITLE
Add new Address on Checkout not working

### ISSUE THREAD

**Issue by matt-h** [hallme/woo-address-book#66]
You can select Add new Address on checkout, but it is no longer saving the address to the address book.

**Comment by woouser** [comment]
Same.

**Comment by matt-h** [comment]
This has been fixed in the 1.7.2 release.

**Comment by woouser** [comment]
﻿It did not work for me. I still can not see my saved addresses.

**Comment by matt-h** [comment]
@woouser this one was fixing saving new addresses not showing in the Address Book, not related to your other issue on here.

**Comment by woouser** [comment]
Ah, ok thank you.
