### ISSUE TITLE
breaks the checkout process with woocomerce updated Version 3.7.1

### ISSUE THREAD

**Issue by ondigusho** [hallme/woo-address-book#67]
[Fri Oct 18 12:25:46.725628 2019] [:error] [pid 3681] [client 127.0.0.1:41376] Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/gon-child/page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/gon/framework/vc_extension/templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/themes/gon/framework/vc_extension/templates/vc_column.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, ts_products_slider_shortcode, wc_get_template_part, load_template, require('/themes/gon-child/woocommerce/content-product.php'), do_action('woocommerce_after_shop_l in /wp-includes/functions.php on line 4231, referer: /checkout/order-received/9136749/?key=wc_order_EHDdx2SGnqhzm

**Comment by matt-h** [comment]
Hi, I do not think your issue is related to this plugin.

Your error is related to a product object and this plugin doesn't touch products at all.

I think from that error that your issue is in the `/themes/gon-child/woocommerce/content-product.php` file.

**Comment by ondigusho** [comment]
Thanks for the tip ! I will look into this. The error triggers only when this plugin is active though. The error : "We were unable to process your order, please try again. " on checkout

**Comment by ondigusho** [comment]
It was some customization on the payment.php that was causing the issue. Thank you. Closing the ticket.
