### ISSUE TITLE
Address book not working in front end

### ISSUE THREAD

**Issue by woouser** [hallme/woo-address-book#68]
Hi,

My addresses do not seem to save or show when using the front end of my website, but if I use the Phone Orders plugin i can save and see all of the saved addresses. how can I get help?

**Comment by woouser** [comment]
<img width="878" alt="Screen Shot 2019-11-04 at 1 56 19 PM" src="https://user-images.githubusercontent.com/57369067/68149284-a0dbe700-ff0b-11e9-8570-10b4ce282bc4.png">
<img width="861" alt="Screen Shot 2019-11-04 at 1 54 58 PM" src="https://user-images.githubusercontent.com/57369067/68149285-a0dbe700-ff0b-11e9-8e57-f0bf24f60458.png">

**Comment by matt-h** [comment]
This is a weird one. Do you see the addresses fine in the Address Book under the "My Account" section?

I'm not familiar with the Phone Orders plugin, but the "Select address book entry" text you have there in your screenshot is not something that is part of this plugin. So is there something else you are using to manage an address book? If so, then that would be a separate address book system then this plugin uses.

**Comment by woouser** [comment]
No, they are not showing up in the addresses section of the user account, and they do not save when I save them either after the update. See screenshot:

<img width="1148" alt="Screen Shot 2019-12-12 at 4 59 02 AM" src="https://user-images.githubusercontent.com/57369067/70702670-9942f700-1c9c-11ea-951f-c9bf69d663e0.png">

I do not use another address plugin, though I have in the past and it has been deleted.

**Comment by matt-h** [comment]
Okay, so this looks like you have the exact same addresses showing in both the part to manage addresses and the checkout of the site. So, that is good that is consistent.
If you add another address with the "Add New Shipping Address" button on that page does it save and show up for you?

What I'm thinking at this point is you added the addresses using another tool or plugin besides this plugin and since this plugin stores addresses in its own format, there are no addresses stored in the format that it can read.

**Comment by woouser** [comment]
No, if i save a new address ir does not show. Also, Phone Orders recommends your plugin to work with theirs. SO I installed yours, and re-added all of the addresses you see in the original post. They are not from the original address plugin i use.

**Comment by woouser** [comment]
HI Matt, any other ideas here? Thanks again!

**Comment by matt-h** [comment]
I'm out of ideas here. From that last screenshot, adding a new address should show it no matter the state the current address book is in (such as addresses saved in an invalid format).

To do any more testing, I'd need to try it out on the site itself or a replica with the same issue to try and re-produce the issue.

**Comment by woouser** [comment]
Sure, i could send credentials to my staging site. please let me know how best to do so confidentially.

**Comment by matt-h** [comment]
You can  email me at matt@hallme.com

**Comment by matt-h** [comment]
Worked with @woouser through email here and it was the woocommerce checkout manager plugin causing the issue of it not working.
