### ISSUE TITLE
Weird message. 

### ISSUE THREAD

**Issue by stpopedavid** [hallme/woo-address-book#7]
What is this message that appears over "Ship to a different address?
Address Book" ( application/x-httpd-php form-shipping.php ( PHP script text ) ) 

Also is there any way to have the address field empty and not auto-populated before a customers select an address?

**Comment by gthayer** [comment]
Hi! Can you please check the CHMOD permissions and make sure they are set to  644 or 777? If that does not work, can you you send us a link or screenshot?

The pre-populated shipping address is handled by Woo itself, not by this plugin. Maybe something like this can work for you? http://www.remicorson.com/how-to-not-pre-populate-woocommerce-checkout-fields/
