### ISSUE TITLE
Address Book placement

### ISSUE THREAD

**Issue by mcatkramer** [hallme/woo-address-book#71]
On our checkout page, the Address Book drop down is located at the bottom of the shipping fields. Any idea why that is and how to fix it? https://shop.alphaprosolutions.com/checkout/ 
We really need it at the top so someone has the ability to choose the address they'd like to use before they go through the process of adding all of their details. 

![image](https://user-images.githubusercontent.com/54155026/69460157-0a942780-0d39-11ea-9221-4a773e520360.png)

**Comment by matt-h** [comment]
Do you have something customizing or modifying the order of your checkout fields? The Address Book field is injected first into the Shipping checkout fields, but if you are using something to reorder or change the checkout fields then that wouldn't know to account for this field.

If needed, you can use the `woocommerce_checkout_fields` filter to re-order your checkout fields.

**Comment by matt-h** [comment]
Closing this due to no reply in over 90 days. Feel free to add a comment if you have more information to add.
