### ISSUE TITLE
Update shipping_address_country_select option text

### ISSUE THREAD

**Issue by dademaru** [hallme/woo-address-book#77]
Hi,

in order to load updated WC translations, `shipping_address_country_select` option text:
`esc_html__( 'Select a country&hellip;', 'woocommerce' )`
on [line 329](https://github.com/hallme/woo-address-book/blob/master/includes/class-wc-address-book.php#L329)
should be updated to:
`esc_html__( 'Select a country / region&hellip;', 'woocommerce' )`
(see [here](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L2706)).

Thanks

**Comment by matt-h** [comment]
Fixed this. Looks like we missed this update that they changed in WooCommerce 4.0

**Comment by dademaru** [comment]
@matt-h 
thanks. Yes, the negative effect of using i18n strings from other plugins (especially WCs) is that they are often modified and need to be updated each time.
It often happens to me too when I use them and at a certain point I realize that they are no longer translated and that I missed the change in the plugin update.
