### ISSUE TITLE
How to migrqte existing address to make it compatable with this plugin

### ISSUE THREAD

**Issue by sunel** [hallme/woo-address-book#99]
I have existing store, I need to migrqte existing address to make it compatable with this plugin?

Any leads?

**Comment by matt-h** [comment]
The default WooCommerce billing and shipping addresses carry over automatically as the fields used are the same.

If you need to import addresses into address books, see this thread for tips on scripting the import: https://wordpress.org/support/topic/add-new-adresses-via-php/
